icon: linux/packaging/gui/logo.png
summary: Remote ZFS Unlock
license: MIT License
group: System/File/Storage/ZFS
vendor: GetBoolean
packager: GetBoolean
url: https://github.com/getBoolean/remote_zfs_unlock

display_name: Remote ZFS Unlock

keywords:
  - ZFS
  - Unlock
  - Remote
  - SSH
  - Utility

generic_name: Remote ZFS Unlock

categories:
  - System
  - File
  - Storage
  - ZFS

startup_notify: true
# You can also specify [metainfo](https://freedesktop.org/software/appstream/docs/chap-Quickstart.html) file
# which contains metadata of the app.
# metainfo: linux/packaging/myappid.appdata.xml
