name: CI
on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Run tests"
        default: true
        required: false
        type: boolean
  push:
    branches:
      - "**"
      - "!gh-pages"
    tags:
      - "v*"

env:
  APP_NAME: "remote_zfs_unlock"
  FLUTTER_CHANNEL: "beta"
  FLUTTER_VERSION: "3.41.0-0.3.pre"
  BRANCH_NAME: $(echo -n ${{ github.head_ref || github.ref_name }} | tr "/" "-")

# Needed to deploy to GitHub Pages
permissions:
  contents: write

jobs:
  flutter_test:
    name: Flutter Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set Variables
        run: |
          echo "BRANCH_NAME=${{ env.BRANCH_NAME }}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ env.BRANCH_NAME }}"

      - name: Print Variables
        run: |
          echo "Flutter Channel: ${{ env.FLUTTER_CHANNEL }}"
          echo "Flutter Version: ${{ env.FLUTTER_VERSION }}"
          echo "Current Branch: ${{ env.BRANCH_NAME }}"

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          flutter-version: ${{env.FLUTTER_VERSION}}
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"

      - name: Check Flutter Version
        run: flutter --version

      - name: Get Packages
        if: github.event.inputs.run_tests == 'true' || github.event.inputs.run_tests == null
        run: flutter pub get

      - name: Generate Code
        if: github.event.inputs.run_tests == 'true' || github.event.inputs.run_tests == null
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run Flutter Tests
        if: github.event.inputs.run_tests == 'true' || github.event.inputs.run_tests == null
        run: flutter test

      - name: Annotate PR
        if: github.event.inputs.run_tests == 'true' || github.event.inputs.run_tests == null
        uses: invertase/github-action-dart-analyzer@v3
        with:
          fatal-infos: false
          fatal-warnings: false
          annotate: true
          annotate-only: true
          # custom-lint: true

  build_web:
    name: Build Flutter for Web
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set Variables
        run: |
          echo "Inputs: ${{ toJSON(github.event.inputs) }}"

          echo "BRANCH_NAME=${{ env.BRANCH_NAME }}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ env.BRANCH_NAME }}"

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          flutter-version: ${{env.FLUTTER_VERSION}}
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"

      - name: Check Flutter Version
        run: flutter --version

      - name: Load Environment Variables
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Build Web
        run: |
          flutter pub get
          flutter build web --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.event.repository.name }}-${{ env.BRANCH_NAME }}-web
          path: build/web

  deploy_web:
    name: Deploy Flutter Web to GitHub Pages
    runs-on: ubuntu-latest
    needs: [build_web]
    permissions:
      pages: write
      id-token: write
      contents: write
      pull-requests: write
      issues: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: github.event_name == 'push' && !startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install and set Flutter version
        if: github.actor != 'dependabot[bot]'
        uses: subosito/flutter-action@v2
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          flutter-version: ${{env.FLUTTER_VERSION}}
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"

      - name: Get branch name
        id: branch-name
        if: github.actor != 'dependabot[bot]'
        uses: tj-actions/branch-names@v9

      - name: Check Flutter Version
        if: github.actor != 'dependabot[bot]'
        run: flutter --version

      - name: Load Environment Variables
        if: github.actor != 'dependabot[bot]'
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Get Dependencies
        if: github.actor != 'dependabot[bot]'
        run: flutter pub get

      - name: Build Web
        if: github.actor != 'dependabot[bot]'
        run: |
          flutter build web --release --base-href="/${{ github.event.repository.name }}/${{ steps.branch-name.outputs.current_branch }}/"

      - name: Deploy to GitHub Pages 🚀
        if: github.actor != 'dependabot[bot]'
        uses: JamesIves/github-pages-deploy-action@releases/v4
        id: deployment
        with:
          token: ${{ secrets.PAT }}
          branch: gh-pages
          folder: build/web
          target-folder: "${{ steps.branch-name.outputs.current_branch }}"

      - name: Find PR Number
        uses: actions/github-script@v8
        id: get_pr_number
        if: github.actor != 'dependabot[bot]' && steps.deployment.outputs.deployment-status == 'success'
        with:
          script: |
            if (context.issue.number) {
              return context.issue.number;
            } else {
              const comment = (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0];

              if (comment != null) {
                return comment.number;
              }
              return null;
            }
          result-encoding: string

      - name: Get PR State
        uses: actions/github-script@v8
        id: get_pr_state
        if: github.actor != 'dependabot[bot]' && steps.get_pr_number.outputs.result != 'null' && steps.deployment.outputs.deployment-status == 'success'
        with:
          script: |
            return (
                await github.rest.issues.get({
                  issue_number: ${{ steps.get_pr_number.outputs.result }},
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data.state;
          result-encoding: string

      - name: Find Comment
        uses: peter-evans/find-comment@v4
        id: comment
        if: github.actor != 'dependabot[bot]' && steps.get_pr_number.outputs.result != 'null' && steps.deployment.outputs.deployment-status == 'success'
        with:
          issue-number: ${{ steps.get_pr_number.outputs.result }}
          body-includes: Deployed to GitHub Pages 🚀
          comment-author: github-actions[bot]

      - name: Link Deployment in Pull Request Comment
        if: github.actor != 'dependabot[bot]' && steps.get_pr_number.outputs.result != 'null' && steps.deployment.outputs.deployment-status == 'success' && steps.get_pr_state.outputs.result == 'open' && steps.comment.outputs.comment-id == ''
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ steps.get_pr_number.outputs.result }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deployed to GitHub Pages 🚀: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ steps.branch-name.outputs.current_branch }}/'
            });

  build_ios_without_signing:
    name: Build Flutter for iOS (Without Signing)
    needs: [flutter_test]
    runs-on: macos-15
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set Variables
        run: |
          echo "BRANCH_NAME=${{ env.BRANCH_NAME }}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ env.BRANCH_NAME }}"

      - name: Install and Setup Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          flutter-version: ${{env.FLUTTER_VERSION}}
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"

      - name: Check Flutter Version
        run: flutter --version

      - name: Get Packages
        run: flutter pub get

      - name: Generate Code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # Zip into IPA from here:
      # https://gist.github.com/devhammed/617d920b7ee886591a46c22633ab0093
      - name: Build Flutter IPA
        run: |
          cd ios && pod deintegrate && pod install && cd ..
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app-release.ipa Payload
          mv app-release.ipa ${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-ios.ipa

      - name: Upload IPA
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-ios
          path: build/ios/iphoneos/${{ env.APP_NAME }}-*.ipa

      - name: Release IPA
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/ios/iphoneos/${{ env.APP_NAME }}-*.ipa
          allowUpdates: true
          omitBodyDuringUpdate: true

  build_android:
    name: Build Flutter for Android
    needs: [flutter_test]
    runs-on: macos-15
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set Variables
        run: |
          echo "BRANCH_NAME=${{ env.BRANCH_NAME }}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ env.BRANCH_NAME }}"

      - name: Install Java JDK
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Check Java Version
        run: |
          java --version
          which java

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          flutter-version: ${{env.FLUTTER_VERSION}}
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"

      - name: Check Flutter Version
        run: flutter --version

      - name: Get Packages
        run: flutter pub get

      - name: Generate Code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # - name: Build Android Split APK
      #   run: |
      #     flutter pub get
      #     flutter build apk --release --split-per-abi
      #     cd build/app/outputs/flutter-apk
      #     mv app-arm64-v8a-release.apk ${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-android-arm64-v8a.apk
      #     mv app-armeabi-v7a-release.apk ${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-android-armeabi-v7a.apk
      #     mv app-x86_64-release.apk ${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-android-x86_64.apk

      # - name: Upload Split APKs
      #   uses: actions/upload-artifact@v7
      #   with:
      #     name: ${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-android-split
      #     path: build/app/outputs/flutter-apk/${{ env.APP_NAME }}-*.apk

      # - name: Release Split APKs
      #   if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: build/app/outputs/flutter-apk/${{ env.APP_NAME }}-*.apk
      #     allowUpdates: true
      #     omitBodyDuringUpdate: true

      - name: Build Universal APK
        run: |
          flutter pub get
          flutter build apk --release
          cd build/app/outputs/flutter-apk
          mv app-release.apk ${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-android-universal.apk

      - name: Upload Universal APK
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-android-universal
          path: build/app/outputs/flutter-apk/${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-android-universal.apk

      - name: Release Universal APKs
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-android-universal.apk
          allowUpdates: true
          omitBodyDuringUpdate: true

      - name: Build Android App Bundle
        run: |
          flutter pub get
          flutter build appbundle --release
          cd build/app/outputs/bundle/release
          mv app-release.aab ${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-android-appbundle.aab

      - name: Upload Android App Bundle
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-android-appbundle
          path: build/app/outputs/bundle/release/*.aab

      - name: Release Android App Bundle
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/bundle/release/${{ env.APP_NAME }}-*.aab
          allowUpdates: true
          omitBodyDuringUpdate: true

  build_windows:
    name: Build Flutter for Windows x64
    needs: [flutter_test]
    runs-on: windows-latest
    steps:
      - name: Enable Git Long Paths
        run: git config --system core.longpaths true

      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set Variables
        run: |
          "BRANCH_NAME=${{ env.BRANCH_NAME }}" | Out-File -Append -LiteralPath $Env:GITHUB_ENV
          Write-Output "BRANCH_NAME=${{ env.BRANCH_NAME }}"
        shell: pwsh

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          flutter-version: ${{env.FLUTTER_VERSION}}
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          architecture: x64

      - name: Check Flutter Version
        run: flutter --version

      - name: Get Packages
        run: flutter pub get

      - name: Generate Code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Windows
        run: flutter build windows --release

      - name: Build MSIX
        run: |
          dart run msix:create --build-windows false
          cd build\windows\x64\runner\Release
          mv *.msix ${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-windows.msix
        shell: pwsh

      - name: Upload MSIX
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-windows
          path: build/windows/x64/runner/Release/*.msix

      - name: Release MSIX
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/windows/x64/runner/Release/${{ env.APP_NAME }}-*.msix
          allowUpdates: true
          omitBodyDuringUpdate: true

  build_linux:
    name: Build Flutter for Linux
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set Variables
        run: |
          echo "BRANCH_NAME=${{ env.BRANCH_NAME }}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ env.BRANCH_NAME }}"

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          flutter-version: ${{env.FLUTTER_VERSION}}
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          architecture: x64

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y webkit2gtk-4.1 clang cmake ninja-build pkg-config libgtk-3-dev mpv libmpv-dev dpkg-dev
          sudo apt-get install -y build-essential libsecret-1-dev libsecret-1-0 libjsoncpp-dev libsecret-tools libusb-dev
          sudo apt-get install -y libfuse2

      - name: Install Snap/LXD
        # Skipping this step as Flutter Snap is broken https://github.com/canonical/flutter-snap/issues/109
        if: false
        run: |
          sudo groupadd --force --system lxd
          sudo usermod --append --groups lxd runner
          sudo snap install lxd
          sudo lxd init --auto
          sudo iptables -P FORWARD ACCEPT
          sudo snap install --channel stable --classic snapcraft

      - name: Check Flutter Version
        run: flutter --version

      - name: Get Packages
        run: flutter pub get

      - name: Generate Code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Linux
        run: flutter build linux --release

      - name: Build AppImage
        run: |
          curl -JOL https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          mv appimagetool-x86_64.AppImage appimagetool

          mv build/linux/x64/release/bundle/{${{ env.APP_NAME }},AppRun}
          cp linux/appimage/* build/linux/x64/release/bundle/
          ./appimagetool build/linux/x64/release/bundle/
          mv *.AppImage build/${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-linux.AppImage

      - name: Upload AppImage
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-linux-appimage
          path: build/${{ env.APP_NAME }}-*.AppImage
          if-no-files-found: error

      - name: Build Snap
        # Skipping this step as Flutter Snap is broken https://github.com/canonical/flutter-snap/issues/109
        if: false
        run: |
          if [ -f snap/snapcraft.yaml ]; then
            if sudo -u runner -E snapcraft pack --destructive-mode; then
              if compgen -G "./*.snap" >/dev/null; then
                mv ./*.snap build/${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-linux.snap
            else
              echo "::warning::Snap build reported success but produced no .snap artifact."
            fi
            else
              echo "::warning::Snap build failed. Skipping Snap artifact for this run."
            fi
          else
            echo "No snap/snapcraft.yaml found - skipping Snap package build."
          fi
      - name: Upload Snap
        # Skipping this step as Flutter Snap is broken https://github.com/canonical/flutter-snap/issues/109
        if: false
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-linux-snap
          path: build/${{ env.APP_NAME }}-*.snap
          if-no-files-found: ignore

      - name: Activate FastForge
        run: dart pub global activate fastforge

      - name: Install FastForge Dependencies
        run: |
          sudo apt install rpm patchelf

      - name: Build Deb
        run: |
          fastforge package --platform linux --targets deb
          mv dist/*/*.deb build/${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-linux.deb

      - name: Upload Deb
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-linux-deb
          path: build/${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-linux.deb
          if-no-files-found: ignore

      - name: Build RPM
        run: |
          fastforge package --platform linux --targets rpm
          mv dist/*/*.rpm build/${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-linux.rpm

      - name: Upload RPM
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-linux-rpm
          path: build/${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-linux.rpm
          if-no-files-found: ignore

      - name: Release Linux Artifacts
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/${{ env.APP_NAME }}-*.AppImage,build/${{ env.APP_NAME }}-*.snap,build/${{ env.APP_NAME }}-*.deb,build/${{ env.APP_NAME }}-*.rpm
          allowUpdates: true
          omitBodyDuringUpdate: true

  build_macos:
    name: Build Flutter for macOS
    needs: [flutter_test]
    runs-on: macos-15
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set Variables
        run: |
          echo "BRANCH_NAME=${{ env.BRANCH_NAME }}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ env.BRANCH_NAME }}"

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          flutter-version: ${{env.FLUTTER_VERSION}}
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          architecture: x64

      - name: Check Flutter Version
        run: flutter --version

      - name: Get Packages
        run: flutter pub get

      - name: Generate Code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build macOS
        run: flutter build macos --release

      - name: Build DMG
        run: |
          brew install create-dmg
          create-dmg \
            --volname "${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-macos" \
            --window-pos 200 120 \
            --window-size 800 450 \
            --icon-size 100 \
            --app-drop-link 600 185 \
            "${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-macos.dmg" \
            "build/macos/Build/Products/Release/${{ env.APP_NAME }}.app"

      - name: Upload DMG
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-macos-dmg
          path: "/Users/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/*.dmg"

      - name: Release DMG
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: /Users/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/${{ env.APP_NAME }}-${{ env.BRANCH_NAME }}-macos.dmg
          allowUpdates: true
          omitBodyDuringUpdate: true

  # build_msix:
  #   name: Build Flutter (Windows MSIX)
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3
  #     - name: Set Variables
  #       run: |
  #         echo "BRANCH_NAME=${{ env.BRANCH_NAME }}" >> $GITHUB_ENV
  #         echo "BRANCH_NAME=${{ env.BRANCH_NAME }}"
  #     # - name: Setup SQLite environment
  #       # uses: ccorsi/setup-sqlite@v1.0.1
  #       # run: |
  #       #   $url = "https://www.sqlite.org/2023/sqlite-dll-win64-x64-3420000.zip"
  #       #   $zip = "$env:TEMP\sqlite-dll-win64-x64-3420000.zip"
  #       #   $dest = "$env:TEMP\sqlite-dll-win64-x64-3420000"
  #       #   Invoke-WebRequest -Uri $url -OutFile $zip
  #       #   Expand-Archive -Path $zip -DestinationPath $dest
  #       #   echo "SQLITE3=$dest\sqlite3.dll" >> $env:GITHUB_ENV
  #     - name: Check SQLite environment
  #       run: |
  #         echo $env:SQLITE3
  #     - name: Setup Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: "stable"
  #     - run: flutter clean
  #     - run: flutter pub get
  #     - run: flutter pub run build_runner build --delete-conflicting-outputs
  #     - name: Build Windows
  #       run: flutter build windows --release
  #     - name: Package as Windows MSIX
  #       run: dart run msix:create
  #     - name: Upload msix
  #       uses: actions/upload-artifact@v7
  #       with:
  #         name: windows_msix
  #         path: build/windows/runner/Release/*.msix
